spring:
  application:
    name: design-api
    http:
      encoding:
        charset: UTF-8
        enabled: true
    jackson:
      serialization:
        write_dates_as_timestamps: false

server:
  servlet:
    context-path: /api

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}